version: '2'
services:

  api:
    build: ./maven
    # restart: always
    volumes:
      - ./_rootfs/root:/root
      - ./_apps/api/:/opt/app

  couchdb:
    image: couchdb:latest
    # restart: always
    volumes:
      - ./_rootfs/root:/root
      - ./_rootfs/var/couchdb:/usr/local/var/lib/couchdb
    environment:
      COUCHDB_USER: "admin"
      COUCHDB_PASSWORD: "q1w2e3r4t5"

  php:
    build: ./php
    # restart: always

    links:
      - api
      - couchdb

    volumes:
      - ./_apps/desafio-php:/var/www/html/app
      - ./_rootfs/root:/root
      - ./_rootfs/etc/php/conf.d/devel.ini:/usr/local/etc/php/conf.d/devel.ini:ro
      - ./_rootfs/etc/php-fpm.d/zz-custom.conf:/usr/local/etc/php-fpm.d/zz-custom.conf:ro

  web:
    image: nginx:mainline-alpine
    # restart: always
    links:
      - api
      - couchdb
      - php
    ports:
      - "80:80"
      # - "443:443"
    volumes:
      - ./_apps/desafio-php:/var/www/html/app
      - ./_rootfs/root:/root
      - ./_rootfs/etc/nginx/conf.d:/etc/nginx/conf.d:ro

  cron:
    build: ./cron
    # restart: always
    volumes:
      - ./_rootfs/root:/root
      - ./_rootfs/respaldo:/respaldo
      - ./_rootfs/var/couchdb:/usr/local/var/lib/couchdb
      - ./cron/scripts:/usr/local/bin
